### ISSUE TITLE
appHasProperty() and levureAppGet() don't handle multidim array?

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#148]
app.yml:
```
helpers:
  - folder: ./helpers
  - filename: "[[FRAMEWORK]]/helpers/preferences"
  - filename: "[[FRAMEWORK]]/helpers/logger"
```

`levureAppHasProperty("helpers>folder")` returns false

`levureAppGet("helpers>folder")` returns nothing
